sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t multi-container-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-container-app-test npm test

after_success:
  - docker build -t schakkadocker/multi-container-client ./client
  - docker build -t schakkadocker/multi-container-nginx ./nginx
  - docker build -t schakkadocker/multi-container-server ./server
  - docker build -t schakkadocker/multi-container-worker ./worker
  # Login to GitBug
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #Push those above images to docker hub
  - docker push schakkadocker/multi-container-client
  - docker push schakkadocker/multi-container-nginx
  - docker push schakkadocker/multi-container-server
  - docker push schakkadocker/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-container-app
  env: MultiContainerApp-env
  bucket_name: elasticbeanstalk-us-east-1-565087585555
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

