sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t multi-container-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true multi-container-app-test npm test

after_success:
  - docker build -t multi-container-client ./client
  - docker build -t multi-container-ngnix ./ngnix
  - docker build -t multi-container-server ./server
  - docker build -t multi-container-worker ./worker
  # Login to GitBug
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  #Push those above images to docker hub
  - docker push multi-container-client
  - docker push multi-container-ngnix
  - docker push multi-container-server
  - docker push multi-container-worker

